# Generated by Django 4.0.2 on 2022-05-29 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyright.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CopyrighterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Уровень копирайтера')),
            ],
            options={
                'verbose_name': 'Уровень копирайтера',
                'verbose_name_plural': 'Уровни копирайтера',
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('keyword', models.CharField(blank=True, max_length=1023, verbose_name='Ключевые слова')),
                ('length', models.PositiveSmallIntegerField(blank=True, verbose_name='Длина статьи')),
                ('execution_time', models.PositiveSmallIntegerField(blank=True, verbose_name='Время выполнения')),
                ('price', models.PositiveSmallIntegerField(blank=True, verbose_name='Цена')),
                ('article', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyright.category')),
                ('copyrighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Копирайтер', to=settings.AUTH_USER_MODEL)),
                ('copyrighter_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyright.copyrighterlevel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Заказчик', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyright.jobstatus')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
